on: ["push"]

jobs:
    arduino-main:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: arduino/compile-sketches@v1
              with:
                  fqbn: "stm32duino:STM32F1:genericSTM32F103C"
                  platforms: |
                      - name: "stm32duino:STM32F1"
                        source-url: "http://dan.drown.org/stm32duino/package_STM32duino_index.json"
                  sketch-paths: |
                      - main
                      - tests/ejection_test
                  libraries: |
                      - name: MPU6050_tockn
                      - name: MS5611
                      - name: Queue
                      - name: SD
                      - source-url: "https://github.com/armtronix/arduino-LoRa-STM32/archive/refs/heads/master.zip"
                      # SPI.h and Wire.h seem to be available per default
                  enable-deltas-report: true
